Add control for FramesSignal.
Ralith/oddio pull request #47
Opened 2021-02-28 20:04 UTC by sanbox-irl

Some thoughts:

1. **Most importantly, I have a 'set_playback_position' but it's not very good.** Right now, it results in an audible "glitch" in my experimenting, and I suspect you'll have opinions on that. I'd be more than happy with removing that and having the rest of the PR accepted. All the other points below this are, in increasing order, bike shedding.
2. I abstracted over the encoded f64, which you might rather do inline yourself. It just made it so I didn't need to touch the sampling code, which I didn't want to touch if I didn't have to. I think this abstraction is fine, and the entire repo uses Relaxed ordering, so I think it's valid, but if you'd like to me split it out, I absolutely can!
3. Speaking of which, most of the API of oddio is in f32s, but FramesSignal worked in f64s previously. I assume we'll still want to be doing that, right? I feel like users can choose to put it in f32 if they want. Alternatively, the getter can return an f32 on its own.
4. Finally, `FramesSignalController` is kind of a long unwieldy name? It's more or less in line with the rest of the codebase though, so I just gave that it that beauty of a name. If you have any inspiration, I have no attachment to it.

Thanks for all your hard work! I appreciate the code review I expect I will undergo from this :))

2021-03-01 06:16 UTC, Ralith commented
Thanks for the PR!

> Most importantly, I have a 'set_playback_position' but it's not very good.

I agree that this is a problem. In particular, as far as I can tell it is *impossible* to use this in a way that even has good odds, let alone a guarantee, of not glitching. Contrast `Cycle` which can do the right thing with carefully-constructed underlying data. We should omit it from this PR, leaving exploration of a crossfading scheme for future work.

> I abstracted over the encoded f64, which you might rather do inline yourself.

No objection. I agree it's cute that the diff doesn't touch the `Signal` impl.

> Speaking of which, most of the API of oddio is in f32s, but FramesSignal worked in f64s previously. I assume we'll still want to be doing that, right?

Yep, this was a deliberate decision because it's not clear to me that a `f32` cursor has enough precision to avoid distorting playback for a very long `Frames`, given that very small errors matter when resampling a high-frequency signal. I'm open to changing it if a careful analysis shows that it's a nonissue for anything that you might sanely want uncompressed in memory all at once.

> Finally, ~`FramesSignalController`~`FramesSignalControl` is kind of a long unwieldy name?

In interface naming, consistency trumps beauty. Further, control names are rarely used downstream, since controls are constructed via `Handle` which keys off the signal type instead. The name in the PR is exactly consistent with the others and hence should remain.

Honestly "FramesSignal" is the real source of ugliness here, but I'm not sure if it can be improved without significantly reduced obviousness.

2021-03-01 18:23 UTC, sanbox-irl commented
So to make sure I'm reading this correctly, the only blocker right now is removing the `set_playback_position` method, right?

2021-03-01 22:54 UTC, Ralith commented
Yep, LGTM otherwise.

2021-03-02 06:09 UTC, sanbox-irl commented
reupped, and good to go! thanks for the code review Ralith :)) that `In interface naming, consistency trumps beauty` is a gem

2021-03-02 07:53 UTC, Ralith requested changes

2021-03-02 07:53 UTC, Ralith commented on src/frames.rs
> +pub struct FramesSignalControl<'a, T>(&'a FramesSignal<T>);
We could drop the type parameter here by wrapping a reference to the `AtomicF64` directly, rather than the entire struct. Makes it harder to accidentally race in the control impl, too.

2021-03-02 09:07 UTC, merged

2021-03-02 09:07 UTC, Ralith commented
Thanks!