FramesSignal::sample optimizations
Ralith/oddio pull request #89
Opened 2022-08-09 22:09 UTC by OlegOAndreev

Hi! While benchmarking various audio libraries I've noticed that the current implementation of `FramesSignal::sample` (which currently consumes most of the time in `oddio::run`) has less than optimal performance. This PR contains substantial performance with minor code changes:
1. Added a few missing `#[inlines]`: the largest perf improvements of 30%-40%
2. Replaced two calls to `Frames::get` with one call `Frames::get_pair`: reduces the number of checks in the fast path (removes a few conditional expressions and allows the optimizer to remove the bound checks), improvement of 5-10%
3. (The least obvious improvement) Replaced f64 with f32 in the main loop in `FramesSignal::sample` by splitting the f64 position into the isize base and the f32 offset. The loss of precision looks extremely minor given that the `sample` should be called frequently with small buffer sizes (a few hundreds milliseconds at most). This removes the f64 -> f32 conversion in inner loop in `Frames::interpolate` and gives another 5-10% perf improvement.
4. (Controversial improvement) Replaced `f32::trunc` with `f32.to_int_unchecked::<isize>`. This massively (30+%) improves performance with default x86-64 builds due to `trunc` being a libm call before x86-64-v2 (SSE4.1). The performance on aarch64 is unchanged. While there are probably almost no pre-SSE4.1 CPUs in active use, I feel that the default experience (running `cargo build` without any flags) matters. The use of unsafe `to_int_unchecked` slightly improves the performance, but it can be changed to `f32 as isize` with minor performance hit.

All the improvements have been tested using three CPUs: Intel Core (MacBook Pro 16 Late 2019), AMD EPYC 7003 (Hetzner Cloud) and Snapdragon 888 (Samsung S21FE).

Similar optimizations (2 and 4 in particular) can be applied to `Stream::sample` as well.

Profile before the changes:
<img width="979" alt="Screenshot 2022-08-07 at 23 15 03" src="https://user-images.githubusercontent.com/149705/183648531-85aacfa7-5f4f-4207-a7b0-13cfb390dccf.png">

Profile after the changes:
<img width="1039" alt="Screenshot 2022-08-09 at 17 48 41" src="https://user-images.githubusercontent.com/149705/183680168-fd87acdf-27c4-4630-b76d-459869dbb6ad.png">

2022-08-09 22:59 UTC, Ralith commented on src/frames.rs
> +        let base = s0.trunc() as isize;
Should we drop the `.trunc()` here too? I don't think it's actually doing anything.

2022-08-09 23:00 UTC, Ralith reviewed
Thanks, this is awesome!

Can you confirm that the inline annotations on generic functions, specifically, have an effect? I'm under the impression that generic functions are de facto implicitly inlined, since they must be monomorphized.

> The loss of precision looks extremely minor ...

Agree that this is a nonissue since you've carefully bounded the magnitude of f32 operations; good catch finding the opportunity.

> The use of unsafe to_int_unchecked slightly improves the performance, but it can be changed to f32 as isize with minor performance hit.

In a lot of ways, `oddio` is my love letter to `unsafe` (and cheeky type erasure), so if there's a measurable benefit and it's clearly sound, I'm on board. `trunc` was clearly inappropriate here. Exactly how big is the difference from `as isize`, though?

2022-08-09 23:03 UTC, OlegOAndreev commented on src/frames.rs
> +        let base = s0.trunc() as isize;
Great question. I believe all instances of `trunc()` in the library can be replaced with simple `as` (or to_int_unchecked, but the latter is mostly important for unblocking autovec e.g. https://rust.godbolt.org/z/9bdjqWjaa)

2022-08-09 23:24 UTC, OlegOAndreev commented
Thanks =) 

> Can you confirm that the inline annotations on generic functions, specifically, have an effect?

Sure, here is a profile of the same benchmark with all the changes from this PR applied:
<img width="814" alt="Screenshot 2022-08-10 at 02 06 02" src="https://user-images.githubusercontent.com/149705/183776847-025eded1-35f7-4b56-9d09-233cb7c3f2ae.png">

> Exactly how big is the difference from as isize, though?

For aarch64 the difference is exactly zero because the ISA is very nice and the float -> int conversion is already saturating: https://rust.godbolt.org/z/bGjnc1M34. For the x86-64 (including the x86-64-v2) the compiler has to add the comparison and the conditional move: https://rust.godbolt.org/z/bnjoeox7Y. In my tests the perf improvement for unsafe version on Intel was ~5%, while the AMD showed ~10% improvement.

2022-08-09 23:35 UTC, Ralith commented
> Sure, here is a profile of the same benchmark with all the changes from this PR applied:

Ah, I see e.g. `lerp` was not inlined before, though `bimap` was. I guess it must be a heuristic weight thing? Well, I'll take it.

> In my tests the perf improvement for unsafe version on Intel was ~5%, while the AMD showed ~10% improvement.

Oh, wow, let's definitely keep that then!

2022-08-10 23:29 UTC, OlegOAndreev commented
I looked around for a bit and took the liberty of improving `Cycles::sample`. Apart from the usual suspects (f64 -> f32, f32::trunc()) it also computed an integer modulo and floating point modulo (the latter becoming a function call into libc both on x86-64 and aarch64) in the inner loop. Replacing floating point modulo with a branch was the most important in this case: 30-50% perf wins.

Here's the profile before removing floating point modulo.
<img width="903" alt="Screenshot 2022-08-11 at 01 26 28" src="https://user-images.githubusercontent.com/149705/184039916-3d039842-5af7-41f6-b8ec-a517966a443a.png">

2022-08-11 17:31 UTC, Ralith reviewed
Nice expansion!

2022-08-11 17:31 UTC, Ralith commented on src/cycle.rs
> +        let fract = sample - a as f64;
Should we move the `f64` arithmetic out of the hot loop using a `base: usize` similarly to `Sample`?

2022-08-11 17:31 UTC, Ralith commented on src/cycle.rs
> +        } else {
How about something like this to make the fastpath a little more common?

```rust
while cursor < out.len() {
    for x in cursor..remaining.min(self.frames.len()) {
        // fill out with contiguous samples ...
    }
    for x in cursor..remaining.min(1) {
        // fill out from wraparound section ...
    }
}
```

Maybe inline `interpolate` entirely at that point, since its inner branch will be redundant.

2022-08-11 23:12 UTC, OlegOAndreev commented on src/cycle.rs
> +        } else {
Thanks for the suggestion! I've rewritten the `Cycle::sample` altogether so that it looks very similar to `FramesSignal::sample`. I've inlined the `interpolate` into `sample` and now we have just one predicted branch on the happy path and performance is equal to `FramesSignal::sample`.

2022-08-11 23:25 UTC, OlegOAndreev commented
On the unrelated note: I tried adding a happy path to the `Gain` (the gain is constant) and probably hit a bug? If the size of out buffer is smaller than the SMOOTHING_PERIOD, then the gain progress gets reset on each `sample` here: https://github.com/Ralith/oddio/blob/main/src/gain.rs#L92 and the gain change looks like alpha^-t, not linear.

2022-08-11 23:31 UTC, OlegOAndreev commented
Back on topic: `play_buffered` in `SpatialScene` is slower than it can be for the usual reasons (too much work done per-sample in `Ring::sample`). The easiest way is probably to copy the chunked sampling from `play` to `play_buffered` and then change `Ring::sample` to output multiple samples at once (the code should be an almost copy-paste from `Cycle::sample`). I can do this if you are ok with these changes.

2022-08-12 17:20 UTC, Ralith requested changes

2022-08-12 17:20 UTC, Ralith commented on src/cycle.rs
> +                offset = (x - self.frames.len()) as f32;
Is this dropping the fractional part of `offset`? That doesn't seem right.

2022-08-12 17:20 UTC, Ralith commented on src/cycle.rs
> +                (self.frames[x], self.frames[x + 1])
If `ds` is larger than `frames.len()` I think this could panic, because `offset` might still be greater than `frames.len()`.

2022-08-12 17:28 UTC, Ralith commented
> I tried adding a happy path to the Gain (for the case when the gain is constant) and probably hit a bug?

Good catch, I can handle the fix for that.

> The easiest way is probably to copy the chunked sampling from play to play_buffered

I'm not sure what this means, but improvements there are certainly welcome, and it makes sense that similar fixes to what you've been doing can be applied. Maybe that should be a separate PR, though? There's a lot of great stuff here I'd like to get merged rather than trapped behind review for independent code.

2022-08-12 18:55 UTC, OlegOAndreev commented
> Maybe that should be a separate PR, though?

Oh, absolutely! This PR is already getting unwieldy.

2022-08-12 21:53 UTC, OlegOAndreev commented on src/cycle.rs
> +                (self.frames[x], self.frames[x + 1])
Thanks, fixed this case and added the tests.

2022-08-12 22:39 UTC, Ralith approved these changes
Great stuff, thank you so much for the contribution!

2022-08-13 01:13 UTC, merged